version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/code/'
    tty: true
    volumes:
      - .:/code
    command: ["python3", "client.py"]

